### ISSUE TITLE
TF UMBRELLA - website setup

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#1]
- [x] create gridsome repo from examplesite
- [x] put structure in place per mockup
- [x] add content per mockup

![TFIO WS REF](https://user-images.githubusercontent.com/20182572/107552423-302a7c80-6bdc-11eb-8732-ad2df7330ded.png)
