### ISSUE TITLE
TF_io update, 5th April

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#58]
**DESCRIPTION:**
Major design and content improvements are needed for our Main website to support Token and Fundraising.

**DEADLINE:**  5th April

**TO DO**:
- [x] Home page updated (design, messaging): https://github.com/threefoldfoundation/www_threefold_io/issues/52 (@ehab-hassan)
- [x] Add Why page: https://github.com/threefoldfoundation/www_threefold_io/issues/53 (@ehab-hassan @samaradel)
- [x] Update / Add Token page: https://github.com/threefoldfoundation/www_threefold_io/issues/54 (@ehab-hassan @Sacha96)
- [x] Minor overall fixes: https://github.com/threefoldfoundation/www_threefold_io/issues/60 (@ehab-hassan)
- [x] Re-work hardcoded image sections: https://github.com/threefoldfoundation/www_threefold_io/issues/59 (@samaradel)
- [x] Update threefold.io/info page: https://github.com/threefoldfoundation/home/issues/144 (@Hamdy @ehab-hassan)
- [x] Update our language on websites: https://github.com/threefoldfoundation/www_threefold_io/issues/36 (@samtaggart @Sacha96)
- [x] Improve token buyer journey: https://github.com/threefoldfoundation/home/issues/158 (@samtaggart @Sacha96)

**Comment by samtaggart** [comment]
@Sacha96 Do you have any updates on #36 or threefoldfoundation/home#158 after your talk with KDS tonight?

**Comment by samtaggart** [comment]
Also @Vilnite I saw some issues with Why & Token page, pointed out to you on Telegram. I imagine it's under control but better safe than sorry

**Comment by Vilnite** [comment]
Created and [issue](https://github.com/threefoldfoundation/www_threefold_io/issues/60), added to this story and it's being addressed already.

**Comment by Sacha96** [comment]
So comments from my call with Kristof are:

NAVBAR updates
1. Add HOME 
2. Change PRODUCTS to UNIVERSE 
3. WHY is good
4. TOKEN is GOOD
5. ECOSYSTEM (remove ACI & TF Tech from dropdown as they are mentioned in universe/products)


UNIVERSE (products right now) page
- Make all images clickable and make text editable 
- I will provide new text in afternoon

WHY PAGE
- Add buttons after Partnerships > [See our partners]  + [Alliance for a Conscious Internet]
<img width="1110" alt="Screenshot 2021-04-06 at 11 47 19" src="https://user-images.githubusercontent.com/54844940/113684388-79231c80-96c5-11eb-81a7-c8aa930721dc.png">

TOKEN PAGE
- Remove Invest. -> A token ... 
<img width="343" alt="Screenshot 2021-04-06 at 11 49 15" src="https://user-images.githubusercontent.com/54844940/113684656-be474e80-96c5-11eb-9b73-41fcea71eb3d.png">

Remove Earn Interest with Staking
- Need to brainstorm around this one with team

Remove BE YOUR OWN BANK and replace with TRULY YOURS
<img width="577" alt="Screenshot 2021-04-06 at 11 54 56" src="https://user-images.githubusercontent.com/54844940/113685425-88ef3080-96c6-11eb-8d80-b38998634c0d.png">

Change EARN INTEREST to BUY TFT <img width="404" alt="Screenshot 2021-04-06 at 11 56 25" src="https://user-images.githubusercontent.com/54844940/113685623-bdfb8300-96c6-11eb-855f-c458271ef4c8.png">

Also we need to find more way to link to explorer and buy token will add here once discussed and agreed with team
