### ISSUE TITLE
TF UMBRELLA - fix bottom of the page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#6]
- [x] Remove TF icon and we need to make image fit whole page again:

<img width="560" alt="Screenshot 2021-02-11 at 09 30 30" src="https://user-images.githubusercontent.com/20182572/107611154-04df7600-6c4c-11eb-9c55-a1178288d5f9.png">

- [x] cta component needs 3 buttons 

- [x] get as close to this as possible:

<img width="801" alt="Screenshot 2021-02-11 at 09 32 40" src="https://user-images.githubusercontent.com/20182572/107611248-3eb07c80-6c4c-11eb-91ca-239576f785cc.png">

**Comment by Vilnite** [comment]
If this is too much of a hustle we can also just take the large image and make it fit whole page on the bottom (just like the one on the top of the page) and move cta component on top of the image, below logos.
