### ISSUE TITLE
TF UMBRELLA - update buttons

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_io#7]
Please update buttons like this:

<img width="398" alt="Screenshot 2021-02-11 at 09 45 26" src="https://user-images.githubusercontent.com/20182572/107612011-f1350f00-6c4d-11eb-873e-ef818641ea53.png">

- [x] for top header component please use one dark one green button:

<img width="493" alt="Screenshot 2021-02-11 at 09 48 17" src="https://user-images.githubusercontent.com/20182572/107612158-4a9d3e00-6c4e-11eb-9a22-1682668b3ddf.png">

- [x] for brandPanel component please use green button
- [x] everywhere else please apply dark button
