### ISSUE TITLE
Planet Positive Peer-to-Peer Internet

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_io#72]
Description: 

Our web presence needs to reflect the new planet positive and sovereign positioning. 

Deliverables:
- [x] Fix language at farming - https://github.com/threefoldfoundation/www_threefold_farming/issues/97
- [x] Edit ThreeFold.io main page https://github.com/threefoldfoundation/www_threefold_io/issues/75
- [x] Review token and why page https://github.com/threefoldfoundation/www_threefold_io/issues/76
- [x] https://github.com/threefoldfoundation/www_threefold_io/issues/78
- [x] Review navigation https://github.com/threefoldfoundation/www_threefold_io/issues/77
- [x] Remove autonomous from learn more -> keep in wiki
- [x] Show the visual of products built on top of ThreeFold Grid
- [x] Ehab & Samar deliver website

Deadline: Sunday 23rd of May

**Comment by Sacha96** [comment]
check language edits doc here: https://docs.google.com/document/d/1QHeu5OsyqDo0E-KkerD2_YZMepB4uKWyBKuua8vQDQQ/edit#
